name: 'build'
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
            version: 8
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install frontend dependencies
        run: pnpm install
      - name: Build app
        run: pnpm tauri build
      - name: Save build artifacts (macos-latest)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
            name: macos
            path: src-tauri/target/release/bundle/dmg/*.dmg
            retention-days: 3
      - name: Save build artifacts (ubuntu-20.04)
        if: matrix.platform == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
            name: linux
            path: |
              src-tauri/target/release/bundle/appimage/*.AppImage
              src-tauri/target/release/bundle/deb/*.deb
            retention-days: 3
      - name: Save build artifacts (windows-latest)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
            name: windows
            path: |
              src-tauri/target/release/bundle/msi/*.msi
              src-tauri/target/release/bundle/nsis/*.exe
            retention-days: 3
